fragment CharacterBreadcrumbs on Character {
  slug
  name
}

fragment ComboCategoryBreadcrumbs on ComboCategory {
  id
  name

  character {
    ...CharacterBreadcrumbs
  }
}

fragment MoveCategoryBreadcrumbs on MoveCategory {
  id
  name

  character {
    ...CharacterBreadcrumbs
  }
}

fragment MoveBreadcrumbs on Move {
  id
  name

  moveCategory {
    ...MoveCategoryBreadcrumbs
  }
}

fragment OrganizerBreadcrumbs on Organizer {
  slug
  name
}

fragment PlayerBreadcrumbs on Player {
  slug
  name
}

fragment TournamentBreadcrumbs on Tournament {
  id
  name
}