export const OperationText: { [name: string]: string } = {
  ub: '↖',
  u: '↑',
  uf: '↗',
  b: '←',
  n: '☆(ニュートラル)',
  f: '→',
  db: '↙',
  d: '↓',
  df: '↘',
  ub_h: '↖(長押し)',
  u_h: '↑(長押し)',
  uf_h: '↗(長押し)',
  b_h: '←(長押し)',
  f_h: '→(長押し)',
  db_h: '↙(長押し)',
  d_h: '↓(長押し)',
  df_h: '↘(長押し)',
  lp: 'LP',
  rp: 'RP',
  lk: 'LK',
  rk: 'RK',
  lp_rp: 'LP+RP',
  lp_lk: 'LP+LK',
  lp_rk: 'LP+RK',
  rp_lk: 'RP+LK',
  rp_rk: 'RP+RK',
  lk_rk: 'LK+RK',
  lp_rp_lk: 'LP+RP+LK',
  lp_rp_rk: 'LP+RP+RK',
  lp_lk_rk: 'LP+LK+RK',
  rp_lk_rk: 'RP+LK+RK',
  lp_rp_lk_rk: 'LP+RP+LK+RK',
  l_bracket: '【',
  r_bracket: '】',
  next: '▶',
};

export const commandText = (command: string[]) => {
  return command.map(o => OperationText[o] || o).join(' ');
};
