fragment ComboDashboardCategory on ComboCategory {
  id
  name
  ...ComboCategoryForm

  combos {
    ...ComboTableRow
  }
}

fragment ComboDashboard on Character {
    id
    slug

    comboCategories {
      ...ComboDashboardCategory
    }

    moveCategories {
      ...MoveSelectOption
    }
}

mutation CreateComboCategory($characterSlug: String!, $attributes: ComboCategoryAttributes!) {
  createComboCategory(input: { characterSlug: $characterSlug, attributes: $attributes }) {
    comboCategory {
      ...ComboDashboardCategory

      character {
        id
        comboCategories {
          id
          position
        }
      }
    }
  }
}

mutation UpdateComboCategory($comboCategoryId: ID!, $attributes: ComboCategoryAttributes!) {
  updateComboCategory(input: { comboCategoryId: $comboCategoryId, attributes: $attributes }) {
    comboCategory {
      ...ComboDashboardCategory

      character {
        id
        comboCategories {
          id
          position
        }
      }
    }
  }
}

mutation DeleteComboCategory($comboCategoryId: ID!) {
  deleteComboCategory(input: { comboCategoryId: $comboCategoryId }) {
    comboCategory {
      ...ComboDashboardCategory

      character {
        id
        comboCategories {
          id
          position
        }
      }
    }
  }
}
