fragment AdminComboCategoriesPageComboCategory on ComboCategory {
  id
  name

  combos {
    ...AdminComboCategoriesPageCombo
  }
}

fragment AdminComboCategoriesPageCombo on Combo {
  id
  command

  comboVideo {
    id
    m3u8Url
    thumbnailUrl
  }

}

query AdminComboCategoriesPage($characterSlug: String!) {
  character(characterSlug: $characterSlug) {
    ...CharacterBreadcrumbs
  }

  comboCategories(characterSlug: $characterSlug) {
    ...AdminComboCategoriesPageComboCategory
  }
}

mutation CreateComboVideo($comboId: ID!) {
  createComboVideo(input: { comboId: $comboId }) {
    combo {
      ...AdminComboCategoriesPageCombo
    }

    videoUpload {
      url
      fields
    }
  }
}

mutation DeleteCombo($comboId: ID!) {
  deleteCombo(input: { comboId: $comboId }) {
    combo {
      id
    }
  }
}
