---
root: true
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - import
  - react
  - jest
settings:
  react:
    version: detect
rules:
  no-console: warn
  semi: off
  yoda: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-empty-function': off
  'react/prop-types': off
  'import/order':
    - warn
    - 'groups': ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'object', 'type']
      'alphabetize': { 'order': 'asc', 'caseInsensitive': true }
      'newlines-between': 'always'
      'pathGroups':
        - 'pattern': 'react'
          'group': 'builtin'
          'position': 'before'
      'pathGroupsExcludedImportTypes': ['react']
