fragment DashboardArticlesPageArticle on Article {
  id
  title
  status
}

mutation DashboardArticlesPagePublish($articleId: ID!) {
  publishArticle(input: { articleId: $articleId }) {
    article {
      ...DashboardArticlesPageArticle
    }
  }
}

mutation DashboardArticlesPageStop($articleId: ID!) {
  stopArticle(input: { articleId: $articleId }) {
    article {
      ...DashboardArticlesPageArticle
    }
  }
}

mutation DashboardArticlesPageDelete($articleId: ID!) {
  deleteArticle(input: { articleId: $articleId }) {
    article {
      id
    }
  }
}

query DashboardArticlesPage($after: String, $keyword: String) {
  myArticles(first: 10, after: $after, keyword: $keyword) {
    edges {
      node { ...DashboardArticlesPageArticle }
      cursor
    }

    pageInfo { ...Pagination }
  }
}
