fragment DashboardArticlesPageArticle on Article {
  id
  title
  status
}

mutation DashboardArticlesPagePublish($articleId: ID!) {
  publishArticle(input: { articleId: $articleId }) {
    article {
      ...DashboardArticlesPageArticle
    }
  }
}

mutation DashboardArticlesPageStop($articleId: ID!) {
  stopArticle(input: { articleId: $articleId }) {
    article {
      ...DashboardArticlesPageArticle
    }
  }
}

mutation DashboardArticlesPageDelete($articleId: ID!) {
  deleteArticle(input: { articleId: $articleId }) {
    article {
      id
    }
  }
}

query DashboardArticlesPage($page: Int = 1, , $keyword: String) {
  myArticles(page: $page, per: 10, , keyword: $keyword) {
    records {
      ...DashboardArticlesPageArticle
    }

    paging {
      ...paging
    }
  }
}
