fragment moveable on Moveable {
  __typename

  ... on AttackMove { ...attackMove }
  ... on ThrowMove { ...throwMove }
  ... on ReversalMove { ...reversalMove }
}

fragment CharacterMovesPageMove on Move {
  id
  name
  kana
  condition
  note

  moveable {
    ...moveable
  }

  commands {
    id

    state {
      id
      name
    }

    operations {
      id
      name
      key
      icon
    }
  }
}

query CharacterMovesPage($characterSlug: String!) {
  character(characterSlug: $characterSlug) {
    ...CharacterBreadcrumbs
    ...CharacterPageProfile

    moveCategories {
      id
      name
      moves {
        ...CharacterMovesPageMove
      }
    }
  }
}
