query AdminBattlesPage($tournamentVideoId: ID!) {
  tournamentVideo(tournamentVideoId: $tournamentVideoId) {
    id
    title
    youtubeVideoId

    tournament {
      id
      name
    }
  }

  players(first: 500) {
    nodes {
      ...PlayerSelectOption
    }
  }

  characters(first: 100) {
    nodes { ...CharacterSelectOption }
  }
}

fragment AdminBattlesPageSide on BattleSide {
  id
  rounds

  player { id name }
  character { id faceImageUrl }
}

fragment AdminBattlesPageBattleReslut on Battle {
  id
  round
  startSec

  sides {
    ...AdminBattlesPageSide
  }
}
query AdminBattlesPageBattles($tournamentVideoId: ID!) {
  battles(tournamentVideoId: $tournamentVideoId, first: 200) {
    nodes {
      ...AdminBattlesPageBattleReslut
    }
  }
}
