query PageAdminMoveEdit($moveId: ID!) {
  move(moveId: $moveId) {
    ...MoveForm

    moveCategory {
      id
      name

      character {
        slug
        name
      }

      moves {
        ...MovePositionSelect
      }
    }
  }
}

mutation UpdateAttackMove($moveId: ID!, $attributes: AttackMoveAttributes!) {
  updateAttackMove(input: { moveId: $moveId, attributes: $attributes }) {
    move {
      id
    }
  }
}

mutation UpdateThrowMove($moveId: ID!, $attributes: ThrowMoveAttributes!) {
  updateThrowMove(input: { moveId: $moveId, attributes: $attributes }) {
    move {
      id
    }
  }
}

mutation UpdateReversalMove($moveId: ID!, $attributes: ReversalMoveAttributes!) {
  updateReversalMove(input: { moveId: $moveId, attributes: $attributes }) {
    move {
      id
    }
  }
}
