version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - type: cache-restore
        key: yarn-cache-{{ checksum "yarn.lock" }}

      - run:
          name: yarn
          command: npm install yarn && yarn

      - type: cache-save
        key: yarn-cache-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

      - run:
          name: tsc
          working_directory: nextjs
          command: npx tsc --noEmit
          when: always

      - run:
          name: eslint
          working_directory: nextjs
          command: yarn eslint
          when: always

      - run:
          name: stylelint
          working_directory: nextjs
          command: yarn stylelint styles/**/*.scss components/**/*.scss
          when: always

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
