query AdminComboCategoryNewPage($characterSlug: String!) {
  character(characterSlug: $characterSlug) {
    ...CharacterBreadcrumbs

    comboCategories {
      ...ComboCategoryPositionSelect
    }
  }
}

mutation CreateComboCategory($characterSlug: String!, $attributes: ComboCategoryAttributes!) {
  createComboCategory(input: { characterSlug: $characterSlug, attributes: $attributes }) {
    comboCategory {
      id
    }
  }
}

mutation DeleteComboCategory($comboCategoryId: ID!) {
  deleteComboCategory(input: { comboCategoryId: $comboCategoryId }) {
    comboCategory {
      id
    }
  }
}
