query DashboardTournamentPage($tournamentId: ID!) {
  tournament(tournamentId: $tournamentId) {
    id
    name
    description
    mainImageUrl
    startsAt
    winningsCount
    videosCount

    videos {
      id
      title
      youtubeVideoId
    }
  }

  players(per: 500) {
    records {
      ...PlayerSelectOption
    }
  }
}

query DashboardTournamentPageWinnings($tournamentId: ID!) {
  winnings(tournamentId: $tournamentId, per: 100) {
    records {
      id
      place

      player {
        id
        name
        avatarUrl
      }
    }
  }
}

query DashboardTournamentPageVideos($tournamentId: ID!) {
  tournamentVideos(tournamentId: $tournamentId) {
    id
    title
    thumbnailUrl
    battlesCount

    channel {
      id
      name
    }
  }
}

mutation DashboardTournamentPageCreateWinning($tournamentId: ID!, $attributes: WinningAttributes!) {
  createWinning(input: { tournamentId: $tournamentId, attributes: $attributes }) {
    winning {
      id
    }
  }
}

mutation DashboardTournamentPageDeleteWinning($winningId: ID!) {
  deleteWinning(input: { winningId: $winningId }) {
    winning {
      id
    }
  }
}


mutation DashboardTournamentPageCreateVideo($tournamentId: ID!, $url: String!) {
  createTournamentVideo(input: { tournamentId: $tournamentId, url: $url }) {
    tournamentVideo {
      id
    }
  }
}

mutation DashboardTournamentPageDeleteVideo($tournamentVideoId: ID!) {
  deleteTournamentVideo(input: { tournamentVideoId: $tournamentVideoId }) {
    tournamentVideo {
      id
    }
  }
}
