fragment attackMove on AttackMove {
  id
  startUpFrame
  duration
  heights
  damages
  reach
  blockResult
  blockStatus
  blockFrame
  hitResult
  hitStatus
  hitFrame
  counterResult
  counterStatus
  counterFrame
  powerCrush
  powerCrushFrame
  crouchingStatus
  crouchingStatusFrame
  jumpStatus
  jumpStatusFrame
  homing
  screw
  wallBound
}

fragment throwMove on ThrowMove {
  id
  throwType
  startUpFrame
  damage
  throwEscape
  throwResult
}

fragment reversalMove on ReversalMove {
  id
  type
  startUpFrame
  finishFrame
}
