fragment attackMove on AttackMove {
  id
  startUpFrame
  heights
  damages
  reach
  blockResult
  blockStatus
  blockFrame
  hitResult
  hitStatus
  hitFrame
  counterResult
  counterStatus
  counterFrame
  powerCrush
  powerCrushFrame
  crouchingStatus
  crouchingStatusFrame
  jumpStatus
  jumpStatusFrame
  homing
  screw
  wallBound
}

fragment throwMove on ThrowMove {
  id
  throwType
  startUpFrame
  damage
  throwEscape
  throwResult
}

fragment reversalMove on ReversalMove {
  id
  type
  startUpFrame
  finishFrame
}

fragment move on Move {
  id
  name
  kana
  command
  statusAfter
  note
  position

  moveCategory {
    id
    name
  }

  moveable {
    __typename

    ... on AttackMove { ...attackMove }
    ... on ThrowMove { ...throwMove }
    ... on ReversalMove { ...reversalMove }
  }

  moveVideo {
    ...moveVideo
  }
}
