fragment DashboardTournamentsPageTournament on Tournament {
  id
  name
  startsAt
  videosCount
  standingsCount
  mainImageUrl
}

query DashboardTournamentsPageTournaments($page: Int = 1, $keyword: String) {
  tournaments(page: $page, per: 10, keyword: $keyword) {
    records {
      ...DashboardTournamentsPageTournament
    }

    paging {
      ...paging
    }
  }
}

mutation DeleteTournament($tournamentId: ID!) {
  deleteTournament(input: { tournamentId: $tournamentId }) {
    tournament {
      id
    }
  }
}
