query PlayerStandingsPage($playerSlug: String!) {
  player(playerSlug: $playerSlug) {
    ...PlayerBreadcrumbs
    ...PlayerProfile
    ...PlayerTabs
  }

  standings(playerSlug: $playerSlug, first: 10) {
    edges {
      node { ...PlayerStandingCard }
      cursor
    }

    pageInfo { ...Pagination }
  }
}

query PlayerStandingsPageStandings($playerSlug: String!, $after: String) {
  standings(playerSlug: $playerSlug, after: $after, first: 10) {
    edges {
      node { ...PlayerStandingCard }
      cursor
    }

    pageInfo { ...Pagination }
  }
}
