fragment CommentCardUser on User {
  name
  avatarUrl
}

fragment ArticleCommentCard on ArticleComment {
  id
  message
  createdAt

  user {
    ...CommentCardUser
  }
}

query ArticleCommentCards($articleId: ID!) {
  articleComments(articleId: $articleId) {
    ...ArticleCommentCard
  }
}

fragment TournamentVideoCommentCard on TournamentVideoComment {
  id
  message
  createdAt

  user {
    ...CommentCardUser
  }
}

query TournamentVideoCommentCards($tournamentVideoId: ID!) {
  tournamentVideoComments(tournamentVideoId: $tournamentVideoId) {
    ...TournamentVideoCommentCard
  }
}