fragment DashboardMoveCategoriesPageMoveCategory on MoveCategory {
  id
  name

  moves {
    ...DashboardMoveCategoriesPageMove
  }
}

fragment DashboardMoveCategoriesPageMove on Move {
  id
  name

  moveVideo {
    ...moveVideo
  }

  commandList {
    ...command
  }
}

query DashboardMoveCategoriesPage($characterSlug: String!) {
  character(characterSlug: $characterSlug) {
    ...CharacterBreadcrumbs
  }

  moveCategories(characterSlug: $characterSlug) {
    ...DashboardMoveCategoriesPageMoveCategory
  }
}