fragment MoveTableRow on Move {
  id
  name
  command

  moveVideo {
    id
    m3u8Url
    thumbnailUrl
  }
}

query MoveTableRows($moveCategoryId: ID!) {
  moves(moveCategoryId: $moveCategoryId) {
    ...MoveTableRow
  }
}

mutation CreateMoveVideo($moveId: ID!) {
  createMoveVideo(input: { moveId: $moveId }) {
    move {
      ...MoveTableRow
    }

    videoUpload {
      url
      fields
    }
  }
}

mutation DeleteMove($moveId: ID!) {
  deleteMove(input: { moveId: $moveId }) {
    move {
      id
    }
  }
}
