query PlayerBattlesPage($playerSlug: String!, $characterSlug: String, $page: Int) {
  player(playerSlug: $playerSlug) {
    ...PlayerBreadcrumbs
    ...PlayerPageProfile

    battleCounts {
      count

      character {
        id
        slug
        name
        faceImageUrl
      }
    }
  }

  battles(playerSlug: $playerSlug, characterSlug: $characterSlug, page: $page, per: 10) {
    records {
      id
      round

      tournamentVideo {
        id

        tournament {
          id
          name
          startsAt
        }
      }

      sides {
        player { name }
        character { faceImageUrl }
        rounds
      }
    }

    paging {
      currentPage
      totalPages
    }
  }
}