query PlayerBattlesPage($playerSlug: String!, $page: Int) {
  player(playerSlug: $playerSlug) {
    ...PlayerBreadcrumbs
    ...PlayerPageProfile
  }

  battleCounts(playerSlug: $playerSlug, per: 10) {
    records { ...CharacterBattleCountChip }
  }


  battles(playerSlug: $playerSlug, page: $page, per: 10) {
    records { ...BattleListItem }
    paging { ...paging }
  }
}

query PlayerBattlesPageBattles($playerSlug: String!, $characterSlug: String, $page: Int!) {

  battles(playerSlug: $playerSlug, characterSlug: $characterSlug, page: $page, per: 10) {
    records { ...BattleListItem }
    paging { ...paging }
  }
}