query AdminTournamentPage($tournamentId: ID!) {
  tournament(tournamentId: $tournamentId) {
    id
    name
    description
    mainImageUrl
    startsAt
    standingsCount
    videosCount

    videos {
      id
      title
      youtubeVideoId
    }
  }
}

query AdminTournamentPageVideos($tournamentId: ID!) {
  tournamentVideos(tournamentId: $tournamentId) {
    nodes {
      id
      title
      thumbnailUrl
      battlesCount

      channel {
        id
        name
      }
    }
  }
}

mutation AdminTournamentPageCreateVideo($tournamentId: ID!, $url: String!) {
  createTournamentVideo(input: { tournamentId: $tournamentId, url: $url }) {
    tournamentVideo {
      id
    }
  }
}

mutation AdminTournamentPageDeleteVideo($tournamentVideoId: ID!) {
  deleteTournamentVideo(input: { tournamentVideoId: $tournamentVideoId }) {
    tournamentVideo {
      id
    }
  }
}
