query AdminTournamentPage($tournamentId: ID!) {
  tournament(tournamentId: $tournamentId) {
    id
    name
    description
    mainImageUrl
    startsAt
    standingsCount
    videosCount

    videos {
      id
      title
      youtubeVideoId
    }
  }

  players(first: 500) {
    nodes {
      ...PlayerSelectOption
    }
  }
}

query AdminTournamentPageStandings($tournamentId: ID!) {
  tournament(tournamentId: $tournamentId) {
    id

    standings {
      id
      place

      player {
        id
        name
        avatarUrl
      }
    }
  }
}

query AdminTournamentPageVideos($tournamentId: ID!) {
  tournamentVideos(tournamentId: $tournamentId) {
    nodes {
      id
      title
      thumbnailUrl
      battlesCount

      channel {
        id
        name
      }
    }
  }
}

mutation AdminTournamentPageCreateStanding($tournamentId: ID!, $attributes: StandingAttributes!) {
  createStanding(input: { tournamentId: $tournamentId, attributes: $attributes }) {
    standing {
      id
    }
  }
}

mutation AdminTournamentPageDeleteStanding($standingId: ID!) {
  deleteStanding(input: { standingId: $standingId }) {
    standing {
      id
    }
  }
}

mutation AdminTournamentPageCreateVideo($tournamentId: ID!, $url: String!) {
  createTournamentVideo(input: { tournamentId: $tournamentId, url: $url }) {
    tournamentVideo {
      id
    }
  }
}

mutation AdminTournamentPageDeleteVideo($tournamentVideoId: ID!) {
  deleteTournamentVideo(input: { tournamentVideoId: $tournamentVideoId }) {
    tournamentVideo {
      id
    }
  }
}
