query DashboardTournamentPage($tournamentId: ID!) {
  tournament(tournamentId: $tournamentId) {
    id
    name
    description
    mainImageUrl
    startsAt
    standingsCount
    videosCount

    videos {
      id
      title
      youtubeVideoId
    }
  }

  players(per: 500) {
    records {
      ...PlayerSelectOption
    }
  }
}

query DashboardTournamentPageStandings($tournamentId: ID!) {
  standings(tournamentId: $tournamentId, per: 100) {
    records {
      id
      place

      player {
        id
        name
        avatarUrl
      }
    }
  }
}

query DashboardTournamentPageVideos($tournamentId: ID!) {
  tournamentVideos(tournamentId: $tournamentId) {
    records {
      id
      title
      thumbnailUrl
      battlesCount

      channel {
        id
        name
      }
    }
  }
}

mutation DashboardTournamentPageCreateStanding($tournamentId: ID!, $attributes: StandingAttributes!) {
  createStanding(input: { tournamentId: $tournamentId, attributes: $attributes }) {
    standing {
      id
    }
  }
}

mutation DashboardTournamentPageDeleteStanding($standingId: ID!) {
  deleteStanding(input: { standingId: $standingId }) {
    standing {
      id
    }
  }
}


mutation DashboardTournamentPageCreateVideo($tournamentId: ID!, $url: String!) {
  createTournamentVideo(input: { tournamentId: $tournamentId, url: $url }) {
    tournamentVideo {
      id
    }
  }
}

mutation DashboardTournamentPageDeleteVideo($tournamentVideoId: ID!) {
  deleteTournamentVideo(input: { tournamentVideoId: $tournamentVideoId }) {
    tournamentVideo {
      id
    }
  }
}
