query DashboardArticlePageArticle($articleId: ID!) {
  article(articleId: $articleId) {
    ...ArticleFormArticle
  }
}

query MyArticle($articleId: ID!) {
  myArticle(articleId: $articleId) {
    id
    title
    description
    mainImageUrl
    publishedAt
    status
    category
    content

    author {
      name
      avatarUrl
    }
  }
}

mutation UpdateArticle($articleId: ID!, $attributes: ArticleAttributes!) {
  updateArticle(input: { articleId: $articleId, attributes: $attributes }) {
    article {
      id
    }
  }
}
