query DashboardBattlesPage($tournamentVideoId: ID!) {
  tournamentVideo(tournamentVideoId: $tournamentVideoId) {
    id
    title
    youtubeVideoId

    tournament {
      id
      name
    }
  }

  players(per: 500) {
    records {
      ...PlayerSelectOption
    }
  }

  characters {
    ...CharacterSelectOption
  }
}

fragment DashboardBattlesPageSide on BattleSide {
  player { id name }
  character { id faceImageUrl }
  rounds
}

fragment DashboardBattlesPageBattleReslut on Battle {
  id
  round
  startSec

  sides {
    ...DashboardBattlesPageSide
  }
}
query DashboardBattlesPageBattles($tournamentVideoId: ID!) {
  battles(tournamentVideoId: $tournamentVideoId, per: 200) {
    records {
      ...DashboardBattlesPageBattleReslut
    }
  }
}