query DashboardTournamentBattlesPage($tournamentVideoId: ID!) {
  tournamentVideo(tournamentVideoId: $tournamentVideoId) {
    id
    title
    youtubeVideoId

    tournament {
      id
      name
    }
  }

  players(per: 500) {
    records {
      ...PlayerSelectOption
    }
  }

  characters {
    ...CharacterSelectOption
  }
}

fragment DashboardTournamentBattlesPageSide on TournamentBattleSide {
  player { id name }
  character { id faceImageUrl }
  rounds
}

fragment DashboardTournamentBattlesPageBattleReslut on TournamentBattle {
  id
  round
  startSec

  sides {
    ...DashboardTournamentBattlesPageSide
  }
}
query DashboardTournamentBattlesPageBattles($tournamentVideoId: ID!) {
  tournamentBattles(tournamentVideoId: $tournamentVideoId, per: 200) {
    records {
      ...DashboardTournamentBattlesPageBattleReslut
    }
  }
}