fragment DashboardPlayersPagePlayer on Player {
  id
  slug
  name
  avatarUrl
}

query DashboardPlayersPagePlayers($page: Int = 1, $keyword: String) {
  players(page: $page, per: 10, keyword: $keyword) {
    records {
      ...DashboardPlayersPagePlayer
    }

    paging {
      ...paging
    }
  }
}

mutation DashboardPlayersPageDelete($playerSlug: String!) {
  deletePlayer(input: { playerSlug: $playerSlug }) {
    player {
      id
    }
  }
}

mutation DashboardPlayersPageCreatePlayerFromSmashgg($smashggId: String!) {
  createPlayerFromSmashgg(input: { smashggId: $smashggId }) {
    player {
      id
    }
  }
}