fragment DashboardComboCategoriesPageComboCategory on ComboCategory {
  id
  name

  combos {
    ...DashboardComboCategoriesPageCombo
  }
}

fragment DashboardComboCategoriesPageCombo on Combo {
  id
  name

  comboVideo {
    ...comboVideo
  }

  command {
    ...command
  }
}


query DashboardComboCategoriesPage($characterSlug: String!) {
  character(characterSlug: $characterSlug) {
    ...CharacterBreadcrumbs
  }

  comboCategories(characterSlug: $characterSlug) {
    ...DashboardComboCategoriesPageComboCategory
  }
}