mutation CreateTournamentBattle($attributes: TournamentBattleAttributes!) {
  createTournamentBattle(input: { attributes: $attributes }) {
    tournamentBattle {
      id
    }
  }
}

mutation UpdateTournamentBattle($tournamentBattleId: ID!, $attributes: TournamentBattleAttributes!) {
  updateTournamentBattle(input: { tournamentBattleId: $tournamentBattleId, attributes: $attributes }) {
    tournamentBattle {
      ...DashboardTournamentBattlesPageBattleReslut
    }
  }
}

mutation DeleteTournamentBattle($tournamentBattleId: ID!) {
  deleteTournamentBattle(input: { tournamentBattleId: $tournamentBattleId }) {
    tournamentBattle {
      id
    }
  }
}