fragment MoveMediaAttack on AttackMove {
  id
  startUpFrame
  duration
  blockFrame
  blockResult
  hitFrame
  hitResult
  counterFrame
  counterResult
  heights
  damages
  powerCrush
  crouchingStatus
  jumpStatus
  homing
  screw
  wallBound
}

fragment MoveMediaThrow on ThrowMove {
  id
  throwType
  throwResult
  throwEscape
  startUpFrame
  damage
}

fragment MoveMediaReversal on ReversalMove {
  id
  kind
  startUpFrame
  finishFrame
}

fragment MoveMedia on Move {
  id
  name
  kana
  command
  statusAfter
  note

  moveable {
    __typename

    ... on AttackMove { ...MoveMediaAttack }
    ... on ThrowMove { ...MoveMediaThrow }
    ... on ReversalMove { ...MoveMediaReversal }
  }

  moveVideo {
    id
    m3u8Url
    thumbnailUrl
  }
}
