fragment PlayerPageProfile on Player {
  id
  name
  slug
  avatarUrl
  twitterId
  streamingUrl
  description
  standingsCount
  battlesCount
}

query PlayerPage($playerSlug: String!) {
  player(playerSlug: $playerSlug) {
    ...PlayerBreadcrumbs
    ...PlayerPageProfile
  }

  standings(playerSlug: $playerSlug, per: 4) {
    records { ...PlayerStandingCard }
    paging { hasNext }
  }

  battles(playerSlug: $playerSlug, per: 4) {
    records { ...BattleListItem }
    paging { hasNext }
  }

  battleCounts(playerSlug: $playerSlug, per: 10) {
    records { ...PlayerBattleCountChip }
  }
}