fragment PlayerTableRow on Player {
  id
  slug
  name
  avatarUrl
}

query PlayerTableRows($after: String, $keyword: String) {
  players(first: 10, after: $after, keyword: $keyword) {
    edges {
      node { ...PlayerTableRow }
      cursor
    }

    pageInfo { ...Pagination }
  }
}

mutation DeletePlayer($playerSlug: String!) {
  deletePlayer(input: { playerSlug: $playerSlug }) {
    player {
      id
    }
  }
}

mutation CreatePlayerFromSmashgg($smashggId: String!) {
  createPlayerFromSmashgg(input: { smashggId: $smashggId }) {
    player {
      id
    }
  }
}
