fragment DashboardMoveCategory on MoveCategory {
  id
  name
  ...MoveCategoryForm

  moves {
    ...MoveTableRow
  }
}

fragment DashboardMoveCategories on Character {
    id
    slug

    moveCategories {
      ...DashboardMoveCategory
    }
}

mutation CreateMoveCategory($characterSlug: String!, $attributes: MoveCategoryAttributes!) {
  createMoveCategory(input: { characterSlug: $characterSlug, attributes: $attributes }) {
    moveCategory {
      ...DashboardMoveCategory

      character {
        id
        moveCategories {
          id
          position
        }
      }
    }
  }
}

mutation UpdateMoveCategory($moveCategoryId: ID!, $attributes: MoveCategoryAttributes!) {
  updateMoveCategory(input: { moveCategoryId: $moveCategoryId, attributes: $attributes }) {
    moveCategory {
      ...DashboardMoveCategory

      character {
        id
        moveCategories {
          id
          position
        }
      }
    }
  }
}

mutation DeleteMoveCategory($moveCategoryId: ID!) {
  deleteMoveCategory(input: { moveCategoryId: $moveCategoryId }) {
    moveCategory {
      ...DashboardMoveCategory

      character {
        id
        moveCategories {
          id
          position
        }
      }
    }
  }
}
