fragment DashboardComboCategoriesPageComboCategory on ComboCategory {
  id
  name

  combos {
    ...DashboardComboCategoriesPageCombo
  }
}

fragment DashboardComboCategoriesPageCombo on Combo {
  id
  command

  comboVideo {
    id
    m3u8Url
    thumbnailUrl
  }

}


query DashboardComboCategoriesPage($characterSlug: String!) {
  character(characterSlug: $characterSlug) {
    ...CharacterBreadcrumbs
  }

  comboCategories(characterSlug: $characterSlug) {
    ...DashboardComboCategoriesPageComboCategory
  }
}