fragment PlayerPageProfile on Player {
  id
  name
  slug
  avatarUrl
  twitterId
  streamingUrl
  description
  tournamentRankingsCount
  battlesCount
}

fragment PlayerPageRanking on TournamentRanking {
  id
  place

  tournament {
    id
    name
    mainImageUrl
    startsAt
  }
}

fragment PlayerPageBattle on Battle {
  id
  round

  tournamentVideo {
    id

    tournament {
      id
      name
      startsAt
    }
  }

  sides {
    player { name }
    character { faceImageUrl }
    rounds
  }
}

query PlayerPage($playerSlug: String!) {
  player(playerSlug: $playerSlug) {
    ...PlayerBreadcrumbs
    ...PlayerPageProfile
  }

  tournamentRankings(playerSlug: $playerSlug, per: 4) {
    records { ...PlayerPageRanking }
    paging { hasNext }
  }

  battles(playerSlug: $playerSlug, per: 4) {
    records { ...PlayerPageBattle }
    paging { hasNext }
  }
}