fragment DashboardMoveCategoriesPageMoveCategory on MoveCategory {
  id
  name

  moves {
    ...DashboardMoveCategoriesPageMove
  }
}

fragment DashboardMoveCategoriesPageMove on Move {
  id
  name
  command

  moveVideo {
    id
    m3u8Url
    thumbnailUrl
  }
}

query DashboardMoveCategoriesPage($characterSlug: String!) {
  character(characterSlug: $characterSlug) {
    ...CharacterBreadcrumbs
  }

  moveCategories(characterSlug: $characterSlug) {
    ...DashboardMoveCategoriesPageMoveCategory
  }
}